package io.tenantlayer.schema;

import io.tenantlayer.core.TenantAwareDataSource;
import java.util.List;

/**
 * Feature 30 — writes the Postgres row-level-security SQL you would otherwise write by
 * hand, once, for review.
 *
 * <h2>Generated, not applied</h2>
 *
 * The output is printed for a human to read, commit and run through their own migration
 * tool. It is deliberately not executed at start-up: applying and verifying policies
 * automatically is feature 32 and is a paid capability, and more to the point, a library
 * that silently issues DDL against a production database is a library nobody should
 * install. Plain SQL also means no lock-in — the policies keep working if TenantLayer is
 * removed.
 *
 * <h2>The three things tutorials get wrong</h2>
 *
 * <ol>
 *   <li><strong>{@code FORCE ROW LEVEL SECURITY}.</strong> Without it the table owner
 *       bypasses the policy, and the application very often connects as the owner. The
 *       policy exists, looks right, and never applies.</li>
 *   <li><strong>{@code nullif(current_setting(...), '')}.</strong> After a reset the
 *       setting reads as an empty string, not NULL. Comparing an empty string to a typed
 *       column errors in the general case, and worse, an unguarded comparison can make
 *       "no tenant" match rows rather than none.</li>
 *   <li><strong>The index.</strong> A policy predicate is applied to every row read. On a
 *       table without an index on the tenant column, isolation turns every lookup into a
 *       sequential scan, and the first person to notice is a customer.</li>
 * </ol>
 */
public class RlsPolicyGenerator {

    private final String setting;

    public RlsPolicyGenerator() {
        this(TenantAwareDataSource.TENANT_SETTING);
    }

    public RlsPolicyGenerator(String setting) {
        this.setting = setting;
    }

    public String generate(List<TenantScopedTable> tables) {
        StringBuilder sql = new StringBuilder();
        sql.append("""
                -- Generated by TenantLayer (feature 30). Review before applying.
                -- Apply through your migration tool, not by hand on a live database.
                """);
        if (tables.isEmpty()) {
            sql.append("\n-- No tenant-scoped tables were found.\n");
            return sql.toString();
        }
        for (TenantScopedTable table : tables) {
            sql.append('\n').append(generateFor(table));
        }
        return sql.toString();
    }

    public String generateFor(TenantScopedTable table) {
        String name = table.tableName();
        String column = table.tenantColumn();
        String policy = name + "_tenant_isolation";

        return """
                -- %s (entity %s)
                create index if not exists idx_%s_%s on %s (%s);

                alter table %s enable row level security;
                alter table %s force row level security;

                drop policy if exists %s on %s;
                create policy %s on %s
                    using (%s = nullif(current_setting('%s', true), ''));
                """.formatted(
                name, table.entityName(),
                name, column, name, column,
                name,
                name,
                policy, name,
                policy, name,
                column, setting);
    }
}
